### ISSUE TITLE
外置播放器不支持电脑端唤起播放器，手机平板端无法显示播放器logo

### ISSUE THREAD

**Issue by autunn** [jackloves111/EMBY.JS.CSS#1]
外置播放器不支持电脑端唤起播放器，手机平板端无法显示播放器logo

**Comment by jackloves111** [comment]
我只是负责整理搬运，原作者ExternalPlayers.js项目地址

https://github.com/Shurelol/ScriptsForEmby/blob/main/ExternalPlayers.js

请到该项目提issues
