### ISSUE TITLE
媒体库较多的情况下，只能等待媒体库切换，能否去掉轮播上的媒体库，这样在开启系统自带媒体库的时候就不会有重复的感觉

### ISSUE THREAD

**Issue by autunn** [jackloves111/EMBY.JS.CSS#2]
媒体库较多的情况下，只能等待媒体库切换，能否去掉轮播上的媒体库，这样在开启系统自带媒体库的时候就不会有重复的感觉

**Comment by jackloves111** [comment]
js 注释第82行，去掉前面的斜杠就可以了
![af8d3d66-01fa-49b4-a880-124b06637260](https://github.com/jackloves111/EMBY.JS.CSS/assets/89971817/0264dbfd-6c45-4305-9949-3396848555ea)

**Comment by autunn** [comment]
啊，站长，我说的不是这个的，我说的是“https://github.com/newday-life/emby-front-end-mod”这一个

**Comment by jackloves111** [comment]
> 啊，站长，我说的不是这个的，我说的是“[https://github.com/newday-life/emby-front-end-mod”这一个](https://github.com/newday-life/emby-front-end-mod%E2%80%9D%E8%BF%99%E4%B8%80%E4%B8%AA)

已经解决了，用我项目里的js文件就可以了

## 如下
https://github.com/newday-life/emby-front-end-mod/issues/3

已解决！打开我的媒体，用css设置横屏时，隐藏即可
![c4739872-4e9e-486b-9338-52cf626e119c](https://github.com/newday-life/emby-front-end-mod/assets/89971817/f79a77cd-1111-445f-9ee9-4347920c2812)


如题添加以上代码
```
	  /*当横屏时，隐藏我的媒体，以免和大图媒体重复*/
          @media not all and (max-width: 50em) {
            .section0 {
              display: none;
          }
```

**Comment by autunn** [comment]
我使用了新的js代码，并添加了
/*当横屏时，隐藏我的媒体，以免和大图媒体重复*/
          @media not all and (max-width: 50em) {
            .section0 {
              display: none;
          }
          }
这一段代码，在电脑网页没有问题，但是手机上无法正常显示

**Comment by jackloves111** [comment]
> 我使用了新的js代码，并添加了 /_当横屏时，隐藏我的媒体，以免和大图媒体重复_/ @media not all and (max-width: 50em) { .section0 { display: none; } } 这一段代码，在电脑网页没有问题，但是手机上无法正常显示

原作者修复了，你可以更新一下

**Comment by autunn** [comment]
还需要添加css吗

**Comment by autunn** [comment]
感谢，已经成功实现了想要的效果，美滋滋
