### ISSUE TITLE
节目界面标签怎么显示多个呀？

### ISSUE THREAD

**Issue by noir1216** [jackloves111/EMBY.JS.CSS#3]
请教一下大佬，节目界面标签怎么显示多个呀？
大佬能给个css代码吗？想显示多个标签，一整行只显示一个标签感觉空空的
![QQ截图20240513173236](https://github.com/jackloves111/EMBY.JS.CSS/assets/44556349/fac28e11-20e1-4249-b20b-3aa2ec4f5a89)

**Comment by jackloves111** [comment]
你不给他加标签，他拿什么显示呢，这个是你搜刮的问题，和css没有关系

**Comment by noir1216** [comment]
![QQ截图20240513175006](https://github.com/jackloves111/EMBY.JS.CSS/assets/44556349/713e62db-6b67-4d4b-b6fe-fae98a7d897f)
